---
dist: trusty
language: node_js
sudo: false
git:
  depth: 5

node_js: stable

cache: yarn

jobs:
  include:
    - stage: Tests
      node_js: '8'
    - node_js: '10'
    - node_js: 'stable'
    - stage: Code Coverage
      node_js: 'stable'
      script: yarn test --ci --coverage
      after_success: npx codecov
