---
dist: trusty
language: node_js
sudo: false
git:
  depth: 5

node_js: stable

cache: yarn

matrix:
  fast_finish: true
  include:
    - node_js: '8'
    - node_js: '9'
    - node_js: 'stable'

jobs:
  include:
    - stage: Code Coverage
      script:
      - yarn test -- --ci --coverage
      - npx codecov
